var express = require('express');
var router = express.Router();
const { transactionController } = require('../controllers');

router.post('/addtocart', transactionController.addtocart);
router.get('/getlistcart/:id', transactionController.getlistcart);
router.get('/getlistcartall/:username', transactionController.getlistcartall);
router.get('/getlistchartagent/:username', transactionController.getlistchartagent);
router.post('/editlistcart', transactionController.editlistcart);
router.post('/deleteitemcart', transactionController.deleteitemcart);
router.post('/addtransaction', transactionController.addtransaction);
router.post('/adddetailtransaction', transactionController.adddetailtransaction);
router.post('/clearcart', transactionController.clearcart);
router.get('/getlistorder/:username', transactionController.getlistorder);
// router.post('/countcart', transactionController.countcart);
router.post('/confirmpayment', transactionController.confirmpayment);
router.post('/getlistpayment', transactionController.getlistpayment);
// router.post('/gethistorytrx', transactionController.gethistorytrx);
// router.post('/gethistorydetail', transactionController.gethistorydetail);
router.post('/ordertoverify', transactionController.getlisttoverify);
router.post('/approvepayment', transactionController.approvepayment);
router.post('/getdataorder',transactionController.getdataorder);
router.post('/getdataorderhistory',transactionController.getdataorderhistory);
router.get('/getlistordercustomer/:id_transaksi', transactionController.getlistordercustomer);
router.post('/getlistordercustomerthismonth', transactionController.getlistordercustomerthismonth);
router.post('/sendstatus', transactionController.sendstatus);
router.post('/sendstatus2', transactionController.sendstatus2);
router.post('/konfirmasipembayaranagent', transactionController.konfirmasipembayaranagent);
router.get('/cukai', transactionController.cukai);
router.post('/cukaiedit', transactionController.editCukai);
router.get('/curency', transactionController.curency);
router.post('/curencyedit', transactionController.editcurency);
router.get('/paket', transactionController.paket);
router.post('/paketedit', transactionController.editPaket);
router.post('/descpaketedit', transactionController.descpaketedit);
router.get('/shipping', transactionController.shipping);
router.post('/shippingedit', transactionController.shippingedit);
router.get('/transactionfee', transactionController.transactionfee);
router.post('/transationedit', transactionController.transationedit);
router.get('/getlistorderdetail/:id_transaksi', transactionController.getlistorderdetail);
router.get('/getreportorder/:id_transaksi', transactionController.getreportorder);
router.post('/getlistordercustomer', transactionController.getlistordercustomerdetail);
router.post('/editcatatancustomer', transactionController.editcatatancustomer);
router.post('/getDataRegister', transactionController.getdataRegisterTotal);
router.post('/autoDelete/transaction', transactionController.autoDelete);
router.get('/getlistordercustomerdetailinvoice/:id_transaksi', transactionController.getInvoice);
router.post('/getAllPaymentOrderHistory', transactionController.allPaymentOrder);
router.post('/getSuperdata', transactionController.toSuperdata);
router.post('/getShopper', transactionController.listPS);
router.post('/getAllcustomer', transactionController.getAllcustomer);
router.post('/getallshopperorder', transactionController.allOrderSdata);
router.post('/getprosesShopper', transactionController.prosesSuperData);
router.post('/updatePengumpulan', transactionController.updatePengumpulan);
router.post('/totalIncome', transactionController.totalIncome);
router.post('/getShippingCustomer' , transactionController.getshippingCustomer);
router.post('/getListShipping', transactionController.getListShipping);
router.post('/getDetailShippingCustomer', transactionController.getDetailShippingCustomer);
router.get('/getHistoryatShopper', transactionController.getHistoryatShopper);
router.get('/getDetailHistoryShopper/:id_tr', transactionController.getDetailHistoryShopper);
router.get('/getConvert', transactionController.getDetailHistoryShopper);
router.post('/getNegaraConvert/', transactionController.getNegaraConvert);
router.get('/getAllItem/:id_customer/:id_negara', transactionController.getAllItem);
router.post('/updatePS', transactionController.updatePS);
router.get('/getAllTrans', transactionController.getAllTrans);
router.get('/getAllJanio/:transaksi', transactionController.getAllJanio);
router.get('/getJanioShopper/:shopper', transactionController.getJanioShopper);
router.get('/getPJTShopper/:shopper', transactionController.getPJTShopper);
router.post('/getTrans', transactionController.getTrans);
router.get('/getCustPjt/:transaksi', transactionController.getCustPjt);
router.post('/getListCustomer', transactionController.getListCustomer);
router.post('/getListEnduser', transactionController.getListEnduser);
router.post('/getBarangEnduser', transactionController.getBarangEnduser);
router.post('/getShopperNegara', transactionController.getShopperNegara);
router.get('/getCustomerInfo/:id_customer/:id_negara/:id_transaksi', transactionController.getCustomerInfo);
router.post('/updateSD', transactionController.updateSD);
router.post('/allClear', transactionController.allClear);
router.post('/getJumlahBarang', transactionController.getJumlahBarang);
router.post('/updatePembagian', transactionController.updatePembagian);
router.post('/allDetailsuperdata', transactionController.allDetailsuperdata);
router.post('/getOneCustomer', transactionController.getOneCustomer);
router.get('/getAllUploadBatch', transactionController.getAllUploadBatch);
router.post('/batalPesanan', transactionController.batalPesanan);

module.exports = router;